### ISSUE TITLE
Example in readme: invalid TypeScript 

### ISSUE THREAD

**Issue by nikitaeverywhere** [InfiniteXyy/zustand-computed-middleware#1]
Hi @InfiniteXyy! Thanks for a nice library.

From the readme, this cannot be used:

<img width="770" alt="image" src="https://user-images.githubusercontent.com/4989256/178660439-1a78fe49-6e83-4f86-98be-3e2495812fd0.png">

Because simply "No overload matches this call". What can I do? Can you provide valid code? Passing properties to the computed function like on the example above makes this library obsolete.

**Comment by InfiniteXyy** [comment]
Hi, thank you for your issue.

I create a demo using the curried function way, and it works fine. I think it is the typescript version that makes the difference, I am using the ts 4.7.3.

https://codesandbox.io/s/zustand-computed-middleware-demo-forked-9wkop4?file=/src/App.tsx

Could you provide a minimum reproducable example?

**Comment by nikitaeverywhere** [comment]
Ah sorry. I thought I did't send this issue through.

After playing a bit I was able to make it work. But please note a lot of readme readers will struggle there for a but too. It's better to provide a simple but complete example instead of (...).


Thanks!

**Comment by InfiniteXyy** [comment]
Thanks for your suggestion!

I have updated the readme in the latest version. (0.2.1)
